# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-14 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bridgetask',
            name='query',
            field=models.TextField(blank=True),
        ),
    ]
