# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-14 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0002_bridgetask_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bridgetask',
            name='ping',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
