# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-14 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0005_auto_20161114_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='bridgetask',
            name='desc',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='minera',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bridgetask',
            name='query',
            field=models.TextField(blank=True, null=True),
        ),
    ]
