# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-17 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0006_auto_20161114_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='typeBridgeTask',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('function', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='bridgetask',
            name='typeTask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bridge.typeBridgeTask'),
        ),
    ]
