# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-18 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0016_auto_20161118_1719'),
        ('bridge', '0016_auto_20161118_1627'),
    ]

    operations = [
    ]
