# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-01 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0035_auto_20161201_1408'),
        ('bridge', '0045_auto_20161201_1324'),
    ]

    operations = [
    ]
