# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-01 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0047_auto_20161201_1419'),
        ('bridge', '0048_auto_20161201_1623'),
    ]

    operations = [
    ]
