# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-22 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0074_auto_20170216_0159'),
    ]

    operations = [
        migrations.CreateModel(
            name='BridgeConnectionLog',
            fields=[
                ('remoteId', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('bridgeName', models.CharField(max_length=150)),
                ('accessTime', models.DateTimeField(auto_now_add=True)),
                ('request', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bridgeresponse',
            name='typeTask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bridge.TypeBridgeTask'),
        ),
        migrations.AlterField(
            model_name='bridgetask',
            name='typeTask',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='bridge.TypeBridgeTask'),
        ),
    ]
