# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0076_auto_20170316_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='bridgeresponse',
            name='results',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bridgetask',
            name='rows',
            field=models.IntegerField(default=10000),
        ),
        migrations.AlterField(
            model_name='bridgeresponse',
            name='typeTask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bridge.TypeBridgeTask'),
        ),
        migrations.AlterField(
            model_name='bridgetask',
            name='typeTask',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='bridge.TypeBridgeTask'),
        ),
    ]
