# Generated by Django 4.2.20 on 2025-03-12 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0079_auto_20170322_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bridgeresponse',
            name='bridge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bridge.minera'),
        ),
        migrations.AlterField(
            model_name='bridgeresponse',
            name='bridgeRequestTask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bridge.bridgetask'),
        ),
        migrations.AlterField(
            model_name='bridgeresponse',
            name='typeTask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bridge.typebridgetask'),
        ),
        migrations.AlterField(
            model_name='bridgetask',
            name='bridge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bridge.minera'),
        ),
        migrations.AlterField(
            model_name='bridgetask',
            name='typeTask',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bridge.typebridgetask'),
        ),
    ]
