# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-05 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='app_theme',
            field=models.CharField(blank=True, choices=[(b'Orange', b'Orange'), (b'Blue', b'Blue'), (b'Lime', b'Lime'), (b'Green', b'Green'), (b'Teal', b'Teal')], default=b"Orange'", max_length=12, verbose_name=b'App Theme'),
        ),
    ]
