# Generated by Django 4.2.20 on 2025-03-12 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0080_alter_bridgeresponse_bridge_and_more'),
        ('users', '0004_userprofile_app_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='app_theme',
            field=models.CharField(blank=True, choices=[('Orange', 'Orange'), ('Blue', 'Blue'), ('Lime', 'Lime'), ('Green', 'Green'), ('Teal', 'Teal')], default="Orange'", max_length=12, verbose_name='App Theme'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bridge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bridge.minera'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='expiration',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha Expiracion'),
        ),
    ]
