# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-19 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bridge', '0024_auto_20161119_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicEndpoint',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('bridge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bridge.Minera')),
            ],
        ),
        migrations.CreateModel(
            name='DynamicGraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('graph_type', models.CharField(blank=True, choices=[(b'LineChart', b'LineChart'), (b'BarChart', b'BarChart'), (b'PieChart', b'PieChart')], max_length=50, verbose_name=b'Graphic type')),
                ('data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bridge.BridgeResponse')),
            ],
        ),
        migrations.AddField(
            model_name='dynamicendpoint',
            name='graphs',
            field=models.ManyToManyField(to='api.DynamicGraph', verbose_name=b'list of graphs'),
        ),
    ]
