# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-19 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20161119_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicendpoint',
            name='slug',
            field=models.SlugField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dynamicgraph',
            name='order',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
