# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-19 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20161119_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dynamicgraph',
            old_name='graph_type',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='dynamicendpoint',
            name='slug',
            field=models.SlugField(help_text=b'Esta ser\xc3\xa1 la url', max_length=150),
        ),
    ]
