# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-19 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20161119_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicgraph',
            name='type',
            field=models.CharField(blank=True, choices=[(b'LineChart', b'LineChart'), (b'BarChart', b'BarChart'), (b'PieChart', b'PieChart'), (b'Table', b'Table')], max_length=50, verbose_name=b'Graphic type'),
        ),
    ]
