# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-29 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20161129_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicgraph',
            name='type',
            field=models.CharField(blank=True, choices=[(b'LineChart', b'LineChart'), (b'BarChart', b'BarChart'), (b'PieChart', b'PieChart'), (b'Table', b'Table'), (b'CustomJson', b'CustomJson'), (b'MineData', b'MineData')], max_length=50, verbose_name=b'Graphic type'),
        ),
    ]
