# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-02 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20161129_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicgraph',
            name='max_x',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='dynamicgraph',
            name='max_y',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='dynamicgraph',
            name='min_x',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='dynamicgraph',
            name='min_y',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
