# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-07 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20161202_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicgraph',
            name='decimals',
            field=models.SmallIntegerField(blank=True, default=2, null=True, verbose_name=b'Numero de decimales'),
        ),
    ]
