# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-09 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_dynamicgraph_decimals'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicgraph',
            name='extra',
            field=models.TextField(blank=True, null=True),
        ),
    ]
