# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-11 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_dynamicgraph_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicgraph',
            name='description',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dynamicgraph',
            name='extra',
            field=models.TextField(blank=True, default=b'\n                                        {\n                                            "label_x": "",\n                                            "label_x": "",\n                                            "zoom": "14",\n                                            "max_x": "0",\n                                            "min_x": "0",\n                                            "max_y": "0",\n                                            "min_y": "0"\n                                        }\n                                        ', help_text=b'<strong>Format:</strong> JSON, <strong>Options:</strong> label_x, label_y, zoom</br>\n                                          ie:<br>{<br>&nbsp;&nbsp;&nbsp;&nbsp;"label_x": "hours",\n                                          </br>&nbsp;&nbsp;&nbsp;&nbsp;"label_y": "shovels"</br>}\n                                          </br></br>\n                                          <strong>Important:</strong> Properties must to be enclosed in double quotes.\n                                          ', null=True),
        ),
    ]
