# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-11 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20170111_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicgraph',
            name='description',
            field=models.CharField(blank=True, default=b'', max_length=150),
        ),
    ]
