# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-16 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20170209_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicendpoint',
            name='icon',
            field=models.CharField(blank=True, choices=[(b'overview', b'overview'), (b'clock', b'clock'), (b'stats', b'stats'), (b'truck', b'truck'), (b'pin', b'pin'), (b'building', b'building'), (b'logout', b'logout')], max_length=30, verbose_name=b'Icon'),
        ),
    ]
