# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-16 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_dynamicendpoint_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicendpoint',
            name='title',
            field=models.CharField(default=b'', help_text=b'Texto que aparece en el menu de la aplicaci\xc3\xb3n', max_length=150),
        ),
        migrations.AlterField(
            model_name='dynamicendpoint',
            name='icon',
            field=models.CharField(blank=True, choices=[(b'generic', b'generic'), (b'overview', b'overview'), (b'clock', b'clock'), (b'stats', b'stats'), (b'truck', b'truck'), (b'pin', b'pin'), (b'building', b'building'), (b'logout', b'logout')], max_length=30, verbose_name=b'Icon'),
        ),
    ]
