# Generated by Django 4.2.20 on 2025-03-12 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0080_alter_bridgeresponse_bridge_and_more'),
        ('api', '0017_auto_20170216_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicendpoint',
            name='bridge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bridge.minera'),
        ),
        migrations.AlterField(
            model_name='dynamicendpoint',
            name='graphs',
            field=models.ManyToManyField(to='api.dynamicgraph', verbose_name='list of graphs'),
        ),
        migrations.AlterField(
            model_name='dynamicendpoint',
            name='icon',
            field=models.CharField(blank=True, choices=[('generic', 'generic'), ('overview', 'overview'), ('clock', 'clock'), ('stats', 'stats'), ('truck', 'truck'), ('pin', 'pin'), ('building', 'building'), ('logout', 'logout')], max_length=30, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='dynamicendpoint',
            name='slug',
            field=models.SlugField(help_text='Esta será la url', max_length=150),
        ),
        migrations.AlterField(
            model_name='dynamicendpoint',
            name='title',
            field=models.CharField(default='', help_text='Texto que aparece en el menu de la aplicación', max_length=150),
        ),
        migrations.AlterField(
            model_name='dynamicgraph',
            name='decimals',
            field=models.SmallIntegerField(blank=True, default=2, null=True, verbose_name='Numero de decimales'),
        ),
        migrations.AlterField(
            model_name='dynamicgraph',
            name='description',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='dynamicgraph',
            name='extra',
            field=models.TextField(blank=True, default='\n                                        {\n                                            "zoom": "14",\n                                            "series": {"y":"", "y2": ""}\n                                        }\n                                        ', help_text='<strong>Format:</strong> JSON</br>\n                                          <strong>Options:</strong> series, table_headers, shovels, label_x, zoom</br>\n                                          </br>\n                                          ie:<br>{<br>&nbsp;&nbsp;&nbsp;&nbsp;"label_x": "hours",\n                                          </br>&nbsp;&nbsp;&nbsp;&nbsp;"table_headers": {\n                                          </br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"header1": ["Movimientos (kt)", "Real (kt)"]\n                                          </br>&nbsp;&nbsp;&nbsp;&nbsp;},\n                                          </br>&nbsp;&nbsp;&nbsp;&nbsp;"shovels": {\n                                          </br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"S01": {"lat": -22.124124, "lon": -69.01120}\n                                          </br>&nbsp;&nbsp;&nbsp;&nbsp;},\n                                          </br>&nbsp;&nbsp;&nbsp;&nbsp;"series": {\n                                          </br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"y": "Movimiento Mina",\n                                          </br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"y2": "Extraccion Mina"\n                                          </br>&nbsp;&nbsp;&nbsp;&nbsp;}</br>}\n                                          </br></br><strong>Important:</strong> Properties must to be enclosed in double quotes.\n                                          ', null=True),
        ),
        migrations.AlterField(
            model_name='dynamicgraph',
            name='type',
            field=models.CharField(blank=True, choices=[('LineChart', 'LineChart'), ('BarChart', 'BarChart'), ('PieChart', 'PieChart'), ('Table', 'Table'), ('CustomJson', 'CustomJson'), ('MineData', 'MineData')], max_length=50, verbose_name='Graphic type'),
        ),
    ]
