# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MineOverview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_total', models.IntegerField(blank=True)),
                ('extraction', models.IntegerField(blank=True)),
                ('min_extracted', models.IntegerField(blank=True)),
                ('min_plant', models.IntegerField(blank=True)),
                ('law_cu_plant', models.IntegerField(blank=True)),
                ('as_ppm', models.IntegerField(blank=True)),
            ],
        ),
    ]
